---
title: "Sesgo y Varianza - Simulaci칩n"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#################################
# Una no lineal
#################################
rm(list=ls())

# Simulaci칩n
sigma <- sqrt(1.3)
beta.star0 <- 0.1
beta.star1 <- 0.025

equis <- seq(1, 10, by=0.1)
set.seed(123)

z <- exp(beta.star0 + beta.star1 * equis * equis)
y <- z + rnorm(length(equis), 0, sigma)

# con puntos
graphics::plot(equis, y, pch=20, col="grey30", xlab="x", ylim=c(0,10))

# grafico la verdadera
lines(equis, z, lwd=2, col="magenta")

#################################
# Ajusto un modelo lineal simple
#################################
salida.lineal <- lm(y ~ equis)
lines(equis, salida.lineal$fitted.values, col="orange", lwd=2)

#################################
# Ajusto un modelo cuadr치tico
#################################
graphics::plot(equis, y, pch=20, col="grey30", xlab="x", ylim=c(0,10))
lines(equis, z, lwd=2)

salida <- lm(y ~ poly(equis, 2, raw=TRUE))
lines(equis, salida$fitted.values, col="orange", lwd=2)

#################################
# Ajusto un polinomio de grado 5
#################################
# E(Y) = beta_0 + beta_1*equis + ... + beta_5*equis^5
# (Completar con el ajuste y gr치fico si es necesario)
```
